package main

import (
	"fmt"
	"github.com/quchunguang/projecteuler"
)

func main() {
	// fmt.Println(projecteuler.PE1(1e3))
	// fmt.Println(projecteuler.PE2(4e6))
	// fmt.Println(projecteuler.PE3(600851475143))
	// fmt.Println(projecteuler.PE4())
	// fmt.Println(projecteuler.PE5(20))
	// fmt.Println(projecteuler.PE6c(100))
	// fmt.Println(projecteuler.PE7(10001))
	// fmt.Println(projecteuler.PE8(13))
	// fmt.Println(projecteuler.PE9(1000))
	// fmt.Println(projecteuler.PE10b())
	// fmt.Println(projecteuler.PE11())
	// fmt.Println(projecteuler.PE12(500))
	// fmt.Println(projecteuler.PE13("p013_bignumbers.txt"))
	// fmt.Println(projecteuler.PE14(1e6))
	// fmt.Println(projecteuler.PE15(20))
	// fmt.Println(projecteuler.PE16(1000))
	// fmt.Println(projecteuler.PE17(1000))
	// fmt.Println(projecteuler.PE18("p018_path.txt"))
	// fmt.Println(projecteuler.PE19b())
	// fmt.Println(projecteuler.PE20(100))
	// fmt.Println(projecteuler.PE21(1e4))
	// fmt.Println(projecteuler.PE22("p022_names.txt"))
	// fmt.Println(projecteuler.PE23())
	// fmt.Println(projecteuler.PE24(1e6))
	// fmt.Println(projecteuler.PE25(1000))
	// fmt.Println(projecteuler.PE26(1000))
	// fmt.Println(projecteuler.PE27())
	// fmt.Println(projecteuler.PE28(1001))
	// fmt.Println(projecteuler.PE29(100))
	// fmt.Println(projecteuler.PE30(5))
	// fmt.Println(projecteuler.PE31(200))
	// fmt.Println(projecteuler.PE32())
	// fmt.Println(projecteuler.PE33())
	// fmt.Println(projecteuler.PE34())
	// fmt.Println(projecteuler.PE35(1e6))
	// fmt.Println(projecteuler.PE36(1e6))
	// fmt.Println(projecteuler.PE37())
	// fmt.Println(projecteuler.PE38())
	// fmt.Println(projecteuler.PE39(1000))
	// fmt.Println(projecteuler.PE40(1e6))
	// fmt.Println(projecteuler.PE41())
	// fmt.Println(projecteuler.PE42("p042_words.txt"))
	// fmt.Println(projecteuler.PE43())
	// fmt.Println(projecteuler.PE44())
	// fmt.Println(projecteuler.PE45())
	// fmt.Println(projecteuler.PE46())
	// fmt.Println(projecteuler.PE47(4))
	// fmt.Println(projecteuler.PE48(1000))
	// fmt.Println(projecteuler.PE49())
	// fmt.Println(projecteuler.PE50(1e6))

	// fmt.Println(projecteuler.PE52())
	// fmt.Println(projecteuler.PE53(1e6))
	// fmt.Println(projecteuler.PE55(1e4))
	// fmt.Println(projecteuler.PE56(100))
	// fmt.Println(projecteuler.PE57(1000))
	// fmt.Println(projecteuler.PE58())
	// fmt.Println(projecteuler.PE59("p059_cipher.txt"))
	// fmt.Println(projecteuler.PE62())
	// fmt.Println(projecteuler.PE63())
	// fmt.Println(projecteuler.PE67("p067_triangle.txt"))
	// fmt.Println(projecteuler.PE97())
	// fmt.Println(projecteuler.PE99("p099_base_exp.txt"))
}
